version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:14.17  # Node.js Docker image
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm test  # Ensure this generates XML test results
      - store_test_results:  # Store test results
          path: ./test-results  # Replace with your test results directory

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build-and-test
      # Include other jobs as needed
